### PR TITLE
Add DSSE

### PR DESCRIPTION
**Pull request by adityasaky**
**Addresses https://github.com/in-toto/in-toto-golang/issues/110**

Note: This code was originally written and contributed to https://github.com/in-toto/in-toto-golang.

Before we merge this, I'd like to hear the best way to credit the original authors of this library. Specifically, @kommendorkapten and friends? If anyone has any recommendations, happy to close this PR and switch to that instead.

cc @SantiagoTorres @trishankatdatadog @mnm678

Please tag anyone I may have forgotten.

### CODE REVIEW

**Comment by kommendorkapten** [comment]
@dlorenc did some work on this too, such as implementing the simpler PAE as defined in DSSEv1 spec.

**Comment by kommendorkapten** [comment]
The git "co-authored-by" mechanism should work I think: https://docs.github.com/en/github/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

**Comment by adityasaky** [comment]
Done. I see GitHub has recognized it and linked it with your accounts :)

**Comment by dlorenc** [comment]
Works for me!

**Comment by adityasaky** [comment]
Thanks @dlorenc and @kommendorkapten!

**Pull request merged**
