### PR TITLE
Support PEM encoding for all key types

### PR DESCRIPTION
**Pull request by adityasaky**
This change matches python-securesystemslib by retiring the custom serialization format. With this change, RSA, ED25519, and ECDSA keys can be loaded from standard PEM encoding, meaning custom tooling isn't needed to generate the keys. This commit adds deprecation warnings to prior Load methods that expected the custom format.

@lukpueh

### CODE REVIEW

**Comment by adityasaky** [comment]
The scheme for ECDSA isn't quite right but I'd prefer to patch that separately.

**Comment by adityasaky** [comment]
Also, the existing test keys were converted using https://github.com/secure-systems-lab/securesystemslib/blob/main/docs/migrate_key.py and checked in.

**Review by mnm678 — APPROVED** [review]

**Comment by adityasaky** [comment]
Converted to draft until @lukpueh gets a chance to review, I don't want this to be merged accidentally. :)

**Comment by adityasaky** [comment]
I've changed the base branch so this can be merged for now. This will enable downstream testing, and we can merge to main after @lukpueh has a chance to review. Thanks @mnm678!

**Pull request merged**
