### PR TITLE
Move cjson code from in-toto-golang

### PR DESCRIPTION
**Pull request by adityasaky**
I've copied `Key` and `KeyVal` from in-toto for the test. We can possibly add some tests from TUF as well?

https://github.com/theupdateframework/go-tuf/issues/180

cc @trishankatdatadog @mnm678 @asraa

### CODE REVIEW

**Comment by asraa** [comment]
Would be good to have something with an embedded json.RawMessage!
https://github.com/theupdateframework/go-tuf/blob/fc0190d925a5f43942c51c5e519b8fce3b025610/data/types.go#L33

**Comment by adityasaky** [comment]
Does https://github.com/secure-systems-lab/go-securesystemslib/pull/10/commits/68a4286549bfce6e97b54b2dee4a99e77b28ed21 suffice?

**Comment by adityasaky** [comment]
Happy to report that it also passes everything in https://github.com/tent/canonical-json-go/blob/master/encode_test.go

**Comment by asraa** [comment]
I think so! thank you

**Comment by adityasaky** [comment]
Cool! I'm going to go ahead and merge this now, since the library has been previously reviewed as part of in-toto-golang...

**Pull request merged**
